version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo prebuild     
  build:
    commands:
      - echo Running build
  post_build:
    commands:
      - echo postbuild

artifacts:
  files:
    - "**/*"
  base-directory: . 
